Add some of the functionality for recent directories
irengrig/vscode pull request #45
Opened 2020-08-24 08:41 UTC by bf319

- Recent directories are stored between sessions. 
- When a file is opened in the editor, its parent directory is marked as 'recent'.
- When a 'recent directory' is opened again, it is moved to the front of the set so as to be marked as 'most recent'.

* A directory should also be marked as 'recent' when it is set as root in the file tree explorer, but this is not included in this commit.

2020-08-24 10:59 UTC, matthiasklostermann approved these changes

2020-08-25 10:24 UTC, irengrig requested changes

2020-08-25 10:24 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesManager.ts
> +		// Directory was already visited recently, move it to the front
I think there is a conceptual problem here.

Here we are taking the set of recent directories (without any information which directory was accessed when and how often), and we only make sure that currently opened directory makes it into the set of limited size.
We do not have the control which directory gets kicked out of the set, however.
it opens a possibility that the directory accessed just-before-current gets kicked out, which is definitely a bug.

2020-08-25 10:24 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesManager.ts
> +	public onOpenedDirectory = this._onOpenedDirectory.event;
Maybe rename to something like 'onRecentDirectoriesChanged' - the event of opening the directory and refreshing the recent directories in not equivalent.
Imagine you opened the editor in directory A (from file tree or code search), did some changes, closed the editor, opened another file in the same directory - the recent directories should not change, but there are 2 events about opening a directory.

2020-08-25 10:24 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesManager.ts
> +			this._onOpenedDirectory.fire({ openedDir: resource, replacedDir: resource });
Firing event should be done only if recent directories changed

2020-08-25 10:43 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesManager.ts
> +		// Directory was already visited recently, move it to the front
The way I was thinking about it was that this set would keep the directories sorted left-to-right by the time they were accessed, with directory at index 0 being the most recent.

When a new directory is opened:
-if it is already in the set no insertion is required, but that directory has to be removed from its current position in the set and added to the front.
-if it was not in the set, then it would be added to the front and the rightmost directory (which is the oldest one) would be popped from the set.

2020-08-25 10:53 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesManager.ts
> +			this._onOpenedDirectory.fire({ openedDir: resource, replacedDir: resource });
Got it. I was doing that because this event is handled in the panel for recent directories, and I wanted to indicate that it has to be re-rendered there from its current position to position 0 (because it is the most recent opened directory). 

I will try to avoid it by changing how filtering happens in the panel.

2020-08-26 12:34 UTC, bf319 commented
I've made a few changes:
- emitters are now stateless, so when the root changes, the new ones are retrieved from explorerService and when the recent directories list changes, these will be retrieved from the recentDirectoriesManager.
- the Set() that keeps recent directories has them sorted in the ordered by date, so that the dir last visited is the one inserted last in the set and the oldest one is at index 0.

2020-08-27 13:46 UTC, irengrig approved these changes
Super, I really like it!)

2020-08-27 13:46 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesManager.ts
> +		return withNullAsUndefined(toResource(input, { supportSideBySide: SideBySideEditor.PRIMARY }));
Looks like this can be omitted:

{ supportSideBySide: SideBySideEditor.PRIMARY }

2020-08-27 13:46 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesManager.ts
> +		if (rawRecentDirectories) {
StorageScope.GLOBAL - should it be workspace storage (or also workspace storage)? we can have a discussion on our meetings:)

2020-08-27 17:30 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesManager.ts
> +		return withNullAsUndefined(toResource(input, { supportSideBySide: SideBySideEditor.PRIMARY }));
Thank you, I did not notice that. I've pushed a new commit to change this.

2020-08-27 17:30 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesManager.ts
> +		if (rawRecentDirectories) {
I'll write this down in the shared doc :)

2020-08-27 17:33 UTC, merged