Added functionality for rendering the list of recent directories in the recent directories panel
irengrig/vscode pull request #46
Opened 2020-08-24 13:44 UTC by bf319

Recent directories are stored in a tree data structure to allow search.

From the recent directories panel, a user can set a dir as root and add / toggle a bookmark.
Dbl click on a directory focuses it in the file explorer.

Handling of recent directories after rendering is implemented.

If a directory does not have a bookmark set, the star outline only appears on mouse hover (this will also be implemented in the file tree).

2020-08-24 14:33 UTC, matthiasklostermann approved these changes

2020-08-25 12:33 UTC, irengrig requested changes

2020-08-25 12:40 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		this._register(this.bookmarksManager.onAddedBookmark(e => {
Is that fired also on bookmark's deletion?

2020-08-26 10:30 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +interface IDirectoryTemplateData {
Yes, I've pushed a new commit where I tried to separate some of the common classes and methods.

Initially I thought it might be weird to reuse the Bookmark class or the renderer for the recent directories, but now I created a common Directory class which both panels can use and an abstract renderer which allows renderElement() to be implemented differently.

2020-08-26 10:31 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +	private _focusIcon!: HTMLElement;
Yes, I've managed to extend that class and just add the new methods for rendering the bookmark

2020-08-26 10:32 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		this._register(this.bookmarksManager.onAddedBookmark(e => {
Yes, because at the moment deletion is implemented as adding a bookmark with type BookmarkType.NONE.

2020-08-26 14:24 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		this._register(this.recentDirectoriesManager.onOpenedDirectory(e => {
Thank you, that was really interesting to learn! I've changed the implementation a new commit.

2020-08-26 14:25 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		rawDirs.forEach(path => this.dirs.unshift({
Use unshift() rather than push() to avoid another call to reverse() at the end.

2020-08-27 14:30 UTC, irengrig approved these changes
Decremental programming in action 👍

2020-08-27 14:30 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +			this.container.insertBefore(this._bookmarkIcon, this.container.firstChild?.nextSibling);
this.container.firstChild?.nextSibling - so we are inserting the bookmark after some first element?
Sorry if I forgot something here.

2020-08-27 14:30 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		this._register(this.bookmarksManager.onAddedBookmark(e => {
We should somehow indicate that;) Otherwise the code reader have to consult what onAddedBookmark() is about, because the reader will also think there should be symmetrical add/remove listeners, or onChange() listener...

2020-08-27 14:47 UTC, irengrig requested changes

2020-08-27 14:47 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		rawDirs.forEach(path => this.dirs.unshift({
Stop, this is N^2:

unshift replaces all the element in array by moving them to the right
please reconsider your algorithm

2020-08-27 17:39 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		rawDirs.forEach(path => this.dirs.unshift({
You're right, this was a big mistake and I should have noticed it. I've just learnt that TypeScript has this unshift() method and I thought it would be better style to push elements to the front and avoid reversing at the end, but I did not give any thought to complexity.

Thank you for noticing! (I'm pretty sure there is one more place, possibly in a different PR, where I do this) 
I will push a new commit to correct this.

2020-08-28 10:03 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +			this.container.insertBefore(this._bookmarkIcon, this.container.firstChild?.nextSibling);
That's because the call to super() in the constructor renders the focus icon as the first child. 

I think it looks better if the bookmark is to the right of the focus icon, especially for directories that are bookmarked (otherwise there would be some space left between the bookmark icon and the directory name, where the focus icon would appear on mouse hover).

2020-08-28 10:15 UTC, bf319 commented
I've changed the use of .unshift() to .push() and then .reverse() after all the elements have been added so that they have the appropriate order.

I did not find any article stating the exact complexity of .push() in JavaScript but I would assume it is amortized O(1) similar to what other languages have (e.g. Java's resizable ArrayList) and this would give O(n) overall cost. One advantage in our case is that n is fixed.

Because we decided to keep the event emitters stateless, this cost will also be incurred every time a new item is inserted but I would think that is fine because the size of the list is static and most likely relatively small (~20 or ~30).

2020-08-28 11:30 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		this._register(this.bookmarksManager.onAddedBookmark(e => {
Got it! For now I have just changed the name of the listener to onBookmarksChanged, but I will refactor the code 
in bookmarksManager.ts a little to separate the addBookmark() and removeBookmark() methods.

2020-08-31 08:55 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +			this.container.insertBefore(this._bookmarkIcon, this.container.firstChild?.nextSibling);
Please modify DirectoryElementIconRenderer to have the field for the focus icon.
(Follow-up change is OK)

2020-08-31 08:55 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +interface IDirectoryTemplateData {
Super! Looks like a lot of work...

2020-08-31 08:59 UTC, irengrig approved these changes

2020-08-31 09:06 UTC, merged