Handle active file not being a child of the current root
irengrig/vscode pull request #50
Opened 2020-08-31 11:11 UTC by bf319

If the active editor file is a child of the current root, then expand all its ancestors up to the root.
Otherwise, set its parent as the new root.

In either case, select the file in the tree.

2020-08-31 11:11 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/common/explorerService.ts
> -			this._onDidChangeRoot.fire();
The event should be triggered after the input has changed.

2020-08-31 11:15 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +				this.explorerService.setRoot(dirname(resource), resource);
There is one way to avoid adding this extra argument to setRoot().

What I've figured is that I can add a listener to explorerService.onDidChangeRoot() and then, whenever the root changes, select the active file from there.

There are some issues with this approach nevertheless. 
(1) This listener would be triggered whenever the root changes and we don't really need this to achieve this functionality
(2) Because the listener is triggered every time (e.g. when you switch root using the focus button), we need to check whether the current active file is a child of the current root (again), otherwise selectResource() would throw an error

The main reason I chose this implementation is to avoid (2), i.e. the extra cost of checking whether the file is a child of the current root.

2020-08-31 11:17 UTC, bf319 commented on src/vs/workbench/contrib/files/common/files.ts
> +	setRoot(resource: URI, selectResource?: URI): void;
If we make the "selectResource" argument optional we can be sure it does not cause any issue to the existing usage of setRoot().

2020-08-31 13:31 UTC, matthiasklostermann approved these changes

2020-08-31 13:31 UTC, matthiasklostermann commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +				this.expandAncestorsToRoot(resource).then(() => this.selectActiveFile(false, true));
For calls with constants as parameters it is sometimes hard to tell what the parameters mean. E.g. for the selectActiveFile(false, true) call, it is hard to guess what false and true mean for the call. In these cases, it helps to have the parameter name as inline-comments. E.g. selectActiveFile(/*paramName1*/ false, /*paramName2*/). (Could not find the actual parameter names, sorry.)

2020-09-01 11:34 UTC, irengrig requested changes

2020-09-01 11:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +				this.expandAncestorsToRoot(resource).then(() => this.selectActiveFile(false, true));
Looks like here is the same pattern: when the promise completes and then() block starts to execute, there is a chance that the tree has already changed.
Should we modify the expandAncestorsToRoot() method as well?

2020-09-01 11:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +				this.expandAncestorsToRoot(resource).then(() => this.selectActiveFile(false, true));
Yes, this is a good idea.

2020-09-01 11:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +				this.explorerService.setRoot(dirname(resource), resource);
Yes, I also think that this additional parameter makes the code simpler.

2020-09-01 11:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/common/explorerService.ts
> +				if (fileToSelect) {
Add here an additional check that the root is still the same as in the arguments - it might have changed, and then we should not select the resource.

2020-09-01 11:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +	private isChildOfCurrentRoot(resource: URI): boolean {
We can use https://github.com/microsoft/vscode/blob/45e6a5e6175709e126dc2bdf09b14986595d09de/src/vs/base/common/resources.ts#L358

2020-09-01 11:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +		while (findAncestor.toString() !== treeInput.resource.toString()) {
extract treeInput.resource.toString() int a const

2020-09-01 14:40 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +				this.expandAncestorsToRoot(resource).then(() => this.selectActiveFile(false, true));
Got it! So modify it in the sense that the selection also happens in that method and before selecting there is another check that the root has not changed, right?

Do you think I should also have checks before using tree.expand() in case the root changes between such calls? I'm thinking that might not be necessary because the calls are awaited and tree.expand() will throw an error if the element is not in the tree, so the other calls (and the selection) would be aborted.

2020-09-02 08:37 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +	private isChildOfCurrentRoot(resource: URI): boolean {
Thank you! I did not know this method already existed.

2020-09-02 12:15 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +			if (rootResource !== currentRoot.resource.toString()) {
If the root has changed here already, just return and don't select the file.

2020-09-03 08:58 UTC, irengrig approved these changes

2020-09-07 10:12 UTC, merged