Refactor the view of the bookmarks in the main file tree
irengrig/vscode pull request #53
Opened 2020-09-01 13:26 UTC by bf319

The scope icon is now rendered on the left, next to the name of the directory.
The bookmark icon is now rendered on the far right and is only visible on mouse hover (if a bookmark is not set, to indicate that the star action can be used to add one).

The indent guides need to be aligned in the abstractTree file and I don't think there is any simple way to avoid modifying that.

2020-09-01 13:27 UTC, bf319 commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +		templateData.twistie.style.paddingLeft = `${indent - 8}px`;
The focus icon (visible or not) already adds extra padding to the file tree, so we need to compensate for that here.

2020-09-01 13:28 UTC, bf319 commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +		templateData.indent.style.paddingLeft = '8px';
The indent guides also need to be aligned and I don't have access to them from the contribution.

2020-09-01 13:31 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/explorerViewer.ts
> +			focusIcon.iconContainer.style.opacity = '0';
'opacity' is never modified so we can ensure the focus icons for files do not become visible.

2020-09-01 16:38 UTC, irengrig requested changes

2020-09-01 16:38 UTC, irengrig commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +		templateData.twistie.style.paddingLeft = `${indent - 8}px`;
I believe there are other visual components in the VSCode using trees - and they will be affected by this change. 
You can not change the padding in the abstract tree unconditionally. 

Also, I was thinking we are now moving all the icon actions to the right?

2020-09-01 16:38 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/explorerView.ts
> +			if (bookmarkIconContainer) {
I guess this DOM.show / DOM.hide methods could be useful here.

2020-09-02 09:38 UTC, bf319 commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +		templateData.twistie.style.paddingLeft = `${indent - 8}px`;
Got it! 

I've been looking into how to avoid this and one way would be to access these elements (the twistie and the indent guides) from explorerViewer, similarly to how rowContainer and contentContainer are accessed here https://github.com/irengrig/vscode/blob/scope_file_tree/src/vs/workbench/contrib/scopeTree/browser/explorerViewer.ts#L447

This would only work if the structure of the elements in the DOM remains the same as it is now, so I will need to have some extra checks for that.

Do you think this implementation would be ok? I realize it's not really the proper solution, but this way we would avoid modifying a base class like abstractTree.

Another possible solution might be to extend the AbstractTree class and override the renderElement() method. Nevertheless, I believe this would also mean extending other classes like WorkbenchCompressibleAsyncDataTree and AsyncDataTree so it might be a little too much considering that we only want to change the padding of an element.

2020-09-02 09:41 UTC, bf319 commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +		templateData.twistie.style.paddingLeft = `${indent - 8}px`;
With regard to the other question: these changes only happen in the main file tree. The focus icon will be rendered on the left, next to the name of the directory (although all the focus icons will be aligned) and the bookmark icon will be rendered on the right (at the far end of the row in the tree).

The other icons have the same positions as they did before. The actions (new file, new folder, ...) are not affected.

2020-09-02 10:53 UTC, irengrig commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +		templateData.twistie.style.paddingLeft = `${indent - 8}px`;
Extending a tree component looks good - but maybe there is a possibility to set a TreeRenderer?

2020-09-02 13:11 UTC, bf319 commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +		templateData.twistie.style.paddingLeft = `${indent - 8}px`;
Yes, that works! I can extend TreeRenderer, change the indent there then change the .map() in the constructor of AbstractTree() to use this new renderer.

2020-09-02 13:54 UTC, bf319 commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +			if (r.templateId === 'file') {
'file' is the id of the FilesRenderer defined in explorerViewer.ts.

I haven't yet figured out a better way to pass this check has to happen in the constructor (so I think using 'options' might not work).

2020-09-03 12:31 UTC, matthiasklostermann approved these changes

2020-09-07 08:20 UTC, irengrig approved these changes
See comment about extract method for possible follow-up

2020-09-07 08:20 UTC, irengrig commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +			if (r.templateId === 'file') {
You could additionally extract a method here 'createTreeRenderer' and redefine it for scope tree.
- it is possible to do it as a follow up change if you want.

2020-09-07 10:19 UTC, bf319 commented on src/vs/base/browser/ui/tree/abstractTree.ts
> +			if (r.templateId === 'file') {
Got it! I've made a new commit to include this.

2020-09-07 10:20 UTC, merged