Blueprints feature
irengrig/vscode pull request #59
Opened 2020-09-09 19:16 UTC by bf319

Added some of the functionality for blueprints.
<li> Bookmarks can be exported and imported</li>
<li> When exported, only files with the extension .bookmarks can be selected for write. If the user chooses an existing file, the bookmarks will be merged with the existing ones and sorted by name. The selected file is also opened after write.</li>
<li> When imported, bookmarks can only be loaded from files with .bookmarks extension</li>

Moved the sorting functionality from BookmarksView to Directory because it needs to be reused in bookmarks.contribution and I feel like it belongs there, as static (I tried to make it as general as possible), rather than with the view.

2020-09-09 19:19 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarksView.ts
> -	private sortBookmarksByName(bookmarks: ITreeElement<Directory>[]): ITreeElement<Directory>[] {
I moved this methods to the Directory class and tried to make them as generic as possible so that they can be static.

This would allow better code reuse and the sorting functionality is not specific to the BookmarksView, so maybe it would be nicer to have it with Directory.

2020-09-09 19:22 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +		const workspaceFolder = contextService.getWorkspace().folders[0];	// This is a placeholder for now
Passing the availableFileSystems option does not work for my in memory file system (I get the error 'No file system provided found for resource vscode-remote'). This also happens if I just try to open a file from the sidebar (where I did no changes).

I believe that if the correct Scheme is passed there for an actual file system this should work without the placeholder.

2020-09-10 14:34 UTC, irengrig requested changes
Cool! Apparently, it was relatively easy (in terms of # of lines)!
Great feature!

2020-09-10 14:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +				if (!newPath) {
Can the user also enter the path with the non-yet-existing directory part?
Maybe it is already handled by VSCode, I do not know.

2020-09-10 14:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +						const prevBookmarks = JSON.parse(blueprintsRaw) as string[];
We are going to replace it with the newline-separated list, do we?

2020-09-10 14:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +		const workspaceBookmarks = bookmarksManager.workspaceBookmarks;
Later we are modifying this object, but this expression does not create a copy. I think it is an error.

2020-09-10 14:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +							workspaceBookmarks.add(bookmark);
This way we can have duplicates - maybe use Set?
Export action is only invoked sometimes, so using additional memory should not be a problem.

2020-09-10 14:34 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +						const toWrite: string[] = Directory.getDirectoriesAsSortedTreeElements(workspaceBookmarks, SortType.NAME)
Sorting array of strings alphabetically should be done without converting it to some other objects and then back... it is an operation that Array.prototype.sort doing, and the sorting function is really easy to code (if you want to keep localeCompare and not default Unicode symbols order)
We need sorting only for the stability of the changes in the bookmarks files, so that multiple exports of the same contents do not change the file etc

2020-09-10 18:26 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +				if (!newPath) {
The name of the file can be changed. From what I can tell, creating directories when saving a file is not implemented (the 'Save As' used in the left sidebar only allows you to choose directories that already exists).

2020-09-10 18:28 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +						const prevBookmarks = JSON.parse(blueprintsRaw) as string[];
The bookmarks appear each one on a new line when they are exported (or merged). The structure is something like:
[
    "bookmark1",
    "bookmark2",
]

2020-09-10 18:47 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +		const workspaceBookmarks = bookmarksManager.workspaceBookmarks;
Thank you so much for catching this! I'll have another commit to correct this.

2020-09-10 18:59 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +						const toWrite: string[] = Directory.getDirectoriesAsSortedTreeElements(workspaceBookmarks, SortType.NAME)
I was doing it this way because bookmarks are strings containing the full path of the directories (but we only need to compare them by their basename()), so if I were to sort the sets as they are there would be 2*n*log(n) calls to basename(). 

I thought it would be worth the conversion back and forth because that requires iterating over the array twice (and creating the objects).

2020-09-10 19:03 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +						const toWrite: string[] = Directory.getDirectoriesAsSortedTreeElements(workspaceBookmarks, SortType.NAME)
Maybe we can discuss it tomorrow? I definitely agree that it can be improved.

2020-09-10 19:05 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +						textFileService.create(newPath, JSON.stringify(toWrite, undefined, '\t' /* Insert tab and new line before resource */)).then(() => editorService.openEditor({ resource: newPath }));
Got it! Initially I separated them because I wanted to use .write() when the file exists and .create() when it doesn't, but .create() also overwrites the file so there should be no problem.

2020-09-10 19:10 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +							workspaceBookmarks.add(bookmark);
workspaceBookmarks is a Set of strings.

prevBookmarks might contain duplicates if someone edited the file manually, but that should not be a problem because all the elements are then added to to workspaceBookmarks.
Do you think it would be worth converting it to a set? I guess there shouldn't be much of a difference and that it would depend on the number of duplicates in the array.

2020-09-10 19:15 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +							workspaceBookmarks.add(bookmark);
Maybe it would be worth converting prevBookmarks to a set as well. What do you think?

2020-09-10 19:18 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +							workspaceBookmarks.add(bookmark);
I'll convert it to a set as well so as to avoid unnecessary calls to .add()

2020-09-11 11:03 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +						const prevBookmarks = JSON.parse(blueprintsRaw) as string[];
We should come to the format with just the paths, separated with new lines, because this way it will be easy to edit them manually

2020-09-11 11:08 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +						const toWrite: string[] = Directory.getDirectoriesAsSortedTreeElements(workspaceBookmarks, SortType.NAME)
Ah yes I forgot about this, you are right => but in the bookmarks file we have different presentation with just the file paths, so I assume it is better to have such a straightforward alphabetic sorting for paths.
let us discuss that in the meeting yes

2020-09-11 11:10 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/bookmarks.contribution.ts
> +				if (!newPath) {
Ok, so it works consistently

2020-09-11 11:12 UTC, irengrig approved these changes
Let us have the possible fixes for sorting in a follow-up PR, approving this one

2020-09-11 11:25 UTC, merged