Solve dark mode issue and mark recent directories that have been deleted
irengrig/vscode pull request #61
Opened 2020-09-11 11:54 UTC by bf319

Change the color used for the scope icon so that it remains visible across all themes.
Remove the background from the breadcrumb so that it inherits the theme's color.

Add a line through recent directories that no longer exist to indicate that (without removing them).
Also handle directories being deleted / added.

Make refreshView() concurrent safe. It only affects the view, not the state, so using a lock should be sufficient.

2020-09-11 11:54 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/media/treeNavigation.css
> -.breadcrumb-background {
This way the breadcrumb background will inherit the colors from the theme.

2020-09-11 11:56 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/directoryViewer.ts
> +	exists: boolean = true;
I gave this field a default value so that it does not affect the other functionality. This property is only modified for views that actually need it (in our case 'exists' is updated in recentDirectoriesView in order to know whether additional decorations should be provided or not).

2020-09-11 12:00 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		});
concurrent calls to refreshView() might make it possible that this.dirs (used below) contains more than 20 elements. 

I think that using a lock (can refresh) should be enough because only the view is modified, and calls to refreshView() retrieve the state from the model which is already updated.

2020-09-11 16:41 UTC, irengrig requested changes

2020-09-11 16:41 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +			title: dir.exists ? undefined : 'Directory was deleted'
Maybe 'does not exist' is better, as it can also be an error with importing manually-edited data

2020-09-11 16:41 UTC, irengrig commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		this.getDirectoriesTreeElement(this.recentDirectoriesManager.recentDirectories).then(() => {
The actual refresh should only be performed once.
This code block makes it so that all calls to refreshView() cause this.getDirectoriesTreeElement() execution, and some of them even two times...

I was expecting that we need to protect a call to this.getDirectoriesTreeElement() from being executed too many times...

My suggestion was the following: allow multiple calls of markDirty() method coming from some events; have the actual refresh delayed and possibly accumulated the signals into just one

boolean dirty = false;

private markDirty() {
  if (! dirty) {
    dirty = true;
    setTimeout(100, refresh);
  }
}

private refresh() {
  if (dirty) {
    dirty = false;
   // actual refresh
  }
}

2020-09-14 08:28 UTC, matthiasklostermann approved these changes

2020-09-14 08:28 UTC, matthiasklostermann commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		private readonly bookmarksManager: IBookmarksManager,
I think there should not be a , at the end of this line.

2020-09-14 08:35 UTC, bf319 commented on src/vs/workbench/contrib/scopeTree/browser/recentDirectoriesView.ts
> +		private readonly bookmarksManager: IBookmarksManager,
Got it! Thank you!

2020-09-14 08:40 UTC, merged